### ISSUE TITLE
Using `environment.yml` does not install pip dependencies

### ISSUE THREAD

**Issue by arokem** [binder-project/binder#21]
Using the conda environment.yml mode for this binder: http://mybinder.org/repo/arokem/white-matter-matters, from this file: https://github.com/arokem/white-matter-matters/blob/master/environment.yml

The conda dependencies do get installed (so `import vtk` works), but pip dependencies are not there ( `import dipy` throws an error).

**Comment by freeman-lab** [comment]
@arokem are we good to say this was resolved by the fixes @ahmadia helped with?

**Comment by arokem** [comment]
Yup! Closing.

**Comment by arokem** [comment]
BTW - vtk still doesn't work for 3D viz, but that's probably another issue - to do with running headless.
